import type { ScopingSession } from '../domain/index.js';
import type { SectionCandidate } from '../domain/deliverables.js';
import { accepted, base, included, known, na, narrative, unresolved } from './shared.js';
export function generateDataIntegrationStrategy(s: ScopingSession): SectionCandidate[] {
  const reqs = included(s); const data = reqs.filter(r => r.type === 'DATA'); const integrations = reqs.filter(r => r.type === 'INT');
  const architecture = accepted(s, 'ArchitectureComponent');
  const database = architecture.find(a => a.sectionKey === 'ARCHITECTURE:database');
  if (!database) throw new Error('Accept the database architecture before strategy generation.');
  const refs = data.length ? data : reqs.filter(r => r.type === 'FR');
  const sections: SectionCandidate[] = [{ ...base('business-data', 'Business records', refs.length ? refs : reqs, 'Persist the records required by the linked workflows; ownership and retention need customer validation.'), artifactKind: 'DATA_STRATEGY', dependencies: [database.id], payload: {
    kind: 'DataDomain', name: 'Workflow business records', sources: [{ kind: 'COMPONENT', sectionId: database.id }], ownership: unresolved(s, 'Identify the business data owner and operational steward.'), ingestion: known('Validate application writes and integration mappings; reject malformed records and retain a recoverable error record.'), storageRefs: [database.id], quality: known('Validate schema, identifiers, referential integrity and duplicate handling; reconcile source and destination records.'), governance: unresolved(s, 'Confirm access policy, data classification and accountable owners; no regulatory framework is assumed.'), metadata: known('Version schemas and record lineage, source system, ingestion timestamp and mapping version.'), retention: unresolved(s, 'Customer retention and deletion policy is not established.'), privacy: known('Minimize personal data, limit access to business purpose and redact operational logs.'), security: known('Encrypt in transit and at rest; restrict credentials and audit privileged access.'), analytics: na('No analytical warehouse or reporting workload is specified; transactional operational views only.'), recovery: known('Use the proposed database backup controls and verify restoration; recovery targets require review.'), flows: [],
  } }];
  for (const r of integrations) {
    const component = architecture.find(a => a.sectionKey === `ARCHITECTURE:integration-${r.id.toLowerCase().replaceAll('_', '-')}`);
    if (!component || component.payload.kind !== 'ArchitectureComponent') throw new Error(`Accept the architecture adapter for ${r.id} before strategy generation.`);
    const external = component.payload.connections.flatMap(c => [c.from, c.to]).find(e => e.kind === 'EXTERNAL_SYSTEM');
    if (!external) throw new Error('Architecture adapter must identify its external system.');
    sections.push({ ...base(`interface-${r.id.toLowerCase().replaceAll('_', '-')}`, `${external.kind === 'EXTERNAL_SYSTEM' ? external.name : r.id} integration`, [r], `Coordinate ${r.id} through the accepted architecture adapter, preserving the same external system and requirement basis.`), artifactKind: 'INTEGRATION_STRATEGY', dependencies: [component.id, 'local:business-data'], payload: { kind: 'Integration', name: external.kind === 'EXTERNAL_SYSTEM' ? external.name : r.id, endpoints: [{ kind: 'COMPONENT', sectionId: component.id }, external], pattern: 'API', dataDomainRefs: ['local:business-data'], authentication: unresolved(s, 'Validate the customer API authentication contract; recommend scoped credentials in Secrets Manager.'), errors: known('Persist categorized failures with correlation IDs; redact sensitive payloads and expose operator remediation.'), retry: known('Use bounded exponential backoff for transient errors, idempotency keys and a dead-letter queue; do not retry authorization failures blindly.'), monitoring: known('Track failed and delayed synchronization with CloudWatch alerts and an assigned operational owner.'), synchronization: known('Map canonical identifiers, retain checkpoints, deduplicate and reconcile source/destination records; resolve conflicting updates with the data owner.') } });
  }
  if (!integrations.length) sections.push(narrative('INTEGRATION_STRATEGY', 'no-integrations', 'Integration applicability', 'INTEGRATIONS', reqs, 'No external integration is required by the reviewed scope.', na('No reviewed INT requirement.')));
  return sections;
}
export function generateAIStrategy(s: ScopingSession): SectionCandidate[] {
  const reqs = included(s); const objective = reqs.filter(r => r.description.includes('draft replies'));
  if (!objective.length) return [narrative('AI_STRATEGY', 'deterministic-strategy', 'Deterministic processing', 'TECHNOLOGIES', reqs, 'Use deterministic validation, workflow rules and API mappings. The reviewed scope provides no AI-specific requirement; no model or AI framework is recommended.', na('No reviewed AI objective.'))];
  const controls = reqs.filter(r => /approve every reply|identifiers|audit trail/.test(r.description));
  const component = accepted(s, 'ArchitectureComponent').find(a => a.sectionKey === 'ARCHITECTURE:ai-model');
  if (!component) throw new Error('Accept the AI architecture component before AI strategy generation.');
  return [{ ...base('support-drafts', 'Support reply drafting', [...objective, ...controls], 'Draft responses from approved articles to support agents; structured validation and human approval control every outgoing reply.'), artifactKind: 'AI_STRATEGY', dependencies: [component.id], technologyChoices: [{ key: 'model-service', target: 'AI', technologyKey: known('aws:bedrock') }], payload: {
    kind: 'AIUseCase', purpose: 'Draft support replies from approved knowledge articles for agent review.', aiRequirementIds: objective.map(r => r.id), deterministicAlternative: known('Search approved articles and use reviewed response templates; preferable where stable rules fully answer the request.'), humanDecisions: known('A support agent must approve every reply before sending; reject or edit incorrect drafts.'), pattern: known('Retrieve approved articles, generate a cited draft, validate a structured response and require explicit human approval.'), modelOptions: known('Evaluate a text generation model available through Amazon Bedrock against the support evaluation set; model/version selection remains a reviewed decision, not a customer mandate.'), frameworkRationale: known('Use the AWS SDK for Bedrock with a small explicit application workflow: this bounded retrieve/draft/review process does not warrant an autonomous agent framework. AWS coupling and model quality require evaluation.'), retrieval: known('Retrieve only approved knowledge articles using the existing article search interface; validate article access and freshness. No vector database is assumed.'), orchestration: known('Deterministic stages: redact identifiers, retrieve approved articles, request draft, validate output, route to human review. The model cannot send replies.'), prompts: known('Version prompt templates; treat tickets/articles as untrusted data and require cited article identifiers.'), outputManagement: known('Validate a strict draft schema with reply text and approved article references; reject unsupported references before review.'), evaluation: known('Test factual support, citation correctness, identifier leakage, injection resistance and agent acceptance on reviewed support examples.'), safety: known('Reject unsupported answers, separate untrusted content from instructions and provide a template fallback; never authorize tools or sending from generated text.'), privacy: known('Remove customer identifiers before model input, minimize retained content and verify provider retention policy before production use.'), monitoring: known('Track invalid outputs, rejected drafts and evaluation regressions without retaining customer identifiers.'), feedback: known('Record approved/rejected draft outcomes for reviewed evaluation updates; do not train automatically on customer content.'), humanReviewControls: known('Approval is mandatory for every reply. The send action requires an explicit support-agent approval record; autonomous sending is prohibited.'),
  } }];
}
