import React, { useEffect, useState } from 'react';
import type { ScopingSession, EstimateItem, EstimateSummary, Range, ArtifactSection } from '../../domain/index.js';
import { api, type Mutate, type ScopeStatus } from '../api.js';
import type { EstimationCommands } from '../../application/estimation.js';
import { SourceEvidence } from './SourceEvidence.js';
import { ArtifactReview } from './ArtifactReview.js';
const format = (r: Range | null | undefined) => r ? `${r.low.toLocaleString('en-US', { maximumFractionDigits: 6 })}–${r.high.toLocaleString('en-US', { maximumFractionDigits: 6 })} ${r.unit}` : 'Unavailable';
const words = (s: string) => s.replace(/([a-z])([A-Z])/g, '$1 $2');
function stored(s: ScopingSession, key: string): unknown { const e = s.configuration.entries[key]; return e?.kind === 'VALUE' && e.value.state === 'KNOWN' ? e.value.value : null; }
function money(r: Range | null, currency: string | null, digits: number | null) { return r && currency && digits !== null ? `${currency} ${(r.low / 10 ** digits).toLocaleString('en-US', { minimumFractionDigits: digits })}–${(r.high / 10 ** digits).toLocaleString('en-US', { minimumFractionDigits: digits })}` : 'Unavailable'; }
export function Estimate({ session: s, mutate, busy, scope }: { session: ScopingSession; mutate: Mutate; busy: boolean; scope: ScopeStatus | null }) {
  const [error, setError] = useState(''); const [confirmed, setConfirmed] = useState(false);
  const [view, setView] = useState<Awaited<ReturnType<EstimationCommands['read']>> | null>(null);
  useEffect(() => { let current = true; void api(`/api/sessions/${s.id}/estimate`).then(v => { if (current) setView(v as NonNullable<typeof view>); }).catch(() => { if (current) setError('Estimation coverage could not be loaded.'); }); return () => { current = false; }; }, [s.id, s.revision]);
  const [rateEdits, setRateEdits] = useState<Record<string, string>>({}); const [contingency, setContingency] = useState(''); const [currency, setCurrency] = useState(''); const [minorDigits, setMinorDigits] = useState('2');
  const [configKey, setConfigKey] = useState('productivity.APPLICATION'); const [configValue, setConfigValue] = useState('1'); const [basis, setBasis] = useState('Reviewer supplied planning assumption');
  const [boundaryType, setBoundaryType] = useState<'DATA' | 'CLOUD'>('DATA'); const [boundaryName, setBoundaryName] = useState(''); const [boundaryText, setBoundaryText] = useState(''); const [boundaryRefs, setBoundaryRefs] = useState<string[]>([]);
  const all = Object.values(s.artifactSections); const units = all.filter(a => a.payload.kind === 'EstimationUnit');
  const items = all.filter((a): a is ArtifactSection & { payload: EstimateItem } => a.payload.kind === 'EstimateItem');
  const summary = all.find(a => a.payload.kind === 'EstimateSummary')?.payload as EstimateSummary | undefined;
  const workstreams = all.filter(a => a.payload.kind === 'Workstream' && a.review === 'REVIEWED');
  const selectedCurrency = stored(s, 'currency') as { code: string; minorUnitDigits: number } | null;
  const disabled = busy || !scope?.eligibility.eligible;
  async function act(path: string, body: object = {}, method: 'POST' | 'PATCH' = 'POST') { setError(''); try { await mutate(`estimate/${path}`, body, method); } catch (e) { setError(e instanceof Error ? e.message : 'Estimate could not be saved.'); } }
  async function update(key: string, value: unknown, why = basis) { await act('configuration', { confirmed: true, updates: [{ key, value, basis: why }] }, 'PATCH'); }
  return <section className="estimate-workspace" aria-label="Deterministic estimate workspace">
    {error && <p role="alert" className="error">{error}</p>}
    {summary && <section className="panel estimate-summary" data-testid="estimate-summary"><div className="row"><h3>Delivery estimate</h3><span className="chip">{summary.resultStatus} · {summary.confidence} confidence</span></div>
      <div className="estimate-metrics"><div><span>Effort</span><strong data-testid="estimate-effort">{format(summary.effort)}</strong><small>{format(summary.presentation?.personWeeks)}</small></div><div><span>Schedule</span><strong>{format(summary.workingDuration)}</strong><small>{format(summary.presentation?.calendarWeeks)}</small></div><div><span>ROM · headline</span><strong>{format(summary.presentation?.rom)}</strong><small data-testid="estimate-rom">Arithmetic: {money(summary.commercials.total, summary.commercials.currency, summary.commercials.minorUnitDigits)}</small></div></div>
      <p>Finish: {summary.finishDates ? `${summary.finishDates.low}–${summary.finishDates.high}` : 'Unavailable'} · Deadline: {summary.deadlineFeasibility}. Indicative planning range, not a delivery commitment.</p>
      <p>Confidence: effort {summary.confidenceByMetric.effort} · timeline {summary.confidenceByMetric.timeline} · commercials {summary.confidenceByMetric.commercials}.</p>
      <p className="muted">{summary.limitations[0]?.reason ?? 'No identified confidence limitation.'}</p>
      <p data-testid="estimate-base">Base commercial: {money(summary.commercials.base, summary.commercials.currency, summary.commercials.minorUnitDigits)} · Contingency: {money(summary.commercials.contingency, summary.commercials.currency, summary.commercials.minorUnitDigits)}</p>
      {summary.resultStatus !== 'COMPLETE' && <p className="error">Full totals are unavailable where inputs are missing. Known partial subtotal: {format(summary.knownSubtotals?.effort)}; priced ROM subtotal: {money(summary.knownSubtotals?.total ?? null, summary.commercials.currency, summary.commercials.minorUnitDigits)}. This is not a full solution estimate.</p>}
    </section>}
    <section className="panel"><h3>Review the estimation basis</h3><p>Deterministic code calculates from accepted scope and delivery workstreams. Review the unit inventory, three Boolean drivers and configuration before calculating.</p><p className="muted">DEMO CONFIGURATION / HEURISTIC DEFAULTS. Baselines and rates are illustrative, not market benchmarks. Excludes cloud operating cost, taxes, licenses, travel and currency conversion.</p>
      <div className="actions"><button disabled={disabled || !workstreams.length} onClick={() => void act('prepare')}>{units.length ? 'Reconcile estimation proposals' : 'Prepare estimation proposals'}</button>{units.length > 0 && <button disabled={disabled} onClick={() => void act('calculate')}>Calculate estimate</button>}</div>
      {!workstreams.length && <p>First propose and accept the delivery workstreams below.</p>}
      {units.length > 0 && <><p>Proposed demo basis includes the displayed Development, Test and Production environments, one security package, and no migration packages unless you add them. Proposed driver values are assumptions, not extracted facts. Unknown readiness remains visible; zero waits are a separate review decision.</p><label className="check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I have reviewed the displayed inventory, boundaries, drivers and configuration, including explicit empty inventories and remaining unknowns.</label><button disabled={disabled || !confirmed} onClick={() => { void act('review', { confirmed: true }); setConfirmed(false); }}>Accept reviewed estimation basis</button></>}
    </section>
    {units.length > 0 && <>
      <section className="panel"><h3>Commercial configuration</h3><p>Rate edits recalculate commercials. Contingency is applied once per canonical unit. Effort remains unchanged.</p>
        <div className="field-grid"><div><label>Currency code<input maxLength={3} value={currency || selectedCurrency?.code || ''} onChange={e => setCurrency(e.target.value.toUpperCase())} /></label><label>Currency minor-unit digits<input type="number" min={0} max={4} value={minorDigits} onChange={e => setMinorDigits(e.target.value)} /></label><button disabled={disabled} onClick={() => void update('currency', { code: currency || selectedCurrency?.code, minorUnitDigits: Number(minorDigits) }, 'Reviewer changed currency/scale; confirm each rate explicitly.')}>Save currency and invalidate rates</button></div><div><label>Contingency percent<input type="number" min={0} max={100} value={contingency || String(stored(s, 'contingencyPercent') ?? '')} onChange={e => setContingency(e.target.value)} /></label><button disabled={disabled} onClick={() => void update('contingencyPercent', contingency === '' ? stored(s, 'contingencyPercent') : Number(contingency), 'Reviewer confirmed contingency percent')}>Save contingency</button></div></div>
        <div className="table-wrap"><table><caption>Role-day rates in integer minor units; explicitly save rates for the selected currency</caption><thead><tr><th>Role</th><th>Rate / person-day</th><th>Currency / review</th><th>Action</th></tr></thead><tbody>{Object.keys(s.configuration.entries).filter(k => k.startsWith('rates.')).sort().map(key => {
          const role = key.slice(6); const rate = stored(s, key) as { amount: number; currency: string } | null;
          return <tr key={key}><td>{role}</td><td><input aria-label={`Rate ${role} minor units per day`} type="number" min={1} step={1} value={rateEdits[role] ?? rate?.amount ?? ''} onChange={e => setRateEdits({ ...rateEdits, [role]: e.target.value })} /></td><td>{rate?.currency ?? 'Unavailable'} · {s.configuration.entries[key]!.validation}</td><td><button disabled={disabled || !selectedCurrency} onClick={() => void update(key, rateEdits[role] === '' ? null : { amount: Number(rateEdits[role] ?? rate?.amount), currency: selectedCurrency!.code, unit: 'minor-units/person-day' }, `Reviewer explicitly confirms ${role} rate in ${selectedCurrency?.code}`)}>Save rate {role}</button><button disabled={disabled} onClick={() => void update(key, null, 'Rate not supplied; block affected ROM')}>Clear rate {role}</button></td></tr>;
        })}</tbody></table></div>
      </section>
      <section className="panel"><h3>Workstreams and canonical units</h3><p>Grouping never changes calculation identity. Quantities are one per included canonical activity.</p>{workstreams.map(ws => {
        if (ws.payload.kind !== 'Workstream') return null; const members = units.filter(u => u.payload.kind === 'EstimationUnit' && u.payload.workstreamId === ws.id);
        const totals = view?.workstreams.find(w => w.id === ws.id);
        return <details key={ws.id} data-testid="estimate-workstream"><summary>{ws.payload.name} · phase {ws.payload.phaseOrder} · {members.length} units · {format(totals?.effort)}</summary><p>Predecessors: {ws.payload.predecessorRefs.join(', ') || 'None'} · Risks: {ws.payload.risks.join('; ')}</p><p>Workstream confidence: {totals?.confidence ?? 'Unavailable'} · ROM: {money(totals?.commercials ?? null, selectedCurrency?.code ?? null, selectedCurrency?.minorUnitDigits ?? null)}</p>{totals?.roleEffort.map(r => <p key={r.roleId}>{r.roleId}: {format(r.effort)}</p>)}{members.map(u => {
          if (u.payload.kind !== 'EstimationUnit') return null; const p = u.payload; const item = items.find(a => a.payload.unitId === u.id)?.payload;
          const sourceIds = p.source.kind === 'DOMAIN' ? [p.source.sectionId] : p.source.kind === 'TEST_TARGET' ? [p.source.unitId] : p.source.kind === 'SOLUTION' ? [] : p.source.scopeRefs;
          return <details className="unit-ledger" id={`unit-${u.id}`} key={u.id} data-testid="estimate-unit"><summary>{u.id} · {u.title} · {p.complexity.band.state === 'KNOWN' ? p.complexity.band.value : 'Unresolved'} · {format(item?.effort)}</summary><p>{p.unitType} · {u.review} · quantity {p.quantity.state === 'KNOWN' ? p.quantity.value : 'Unknown'} · {p.inclusion.state === 'KNOWN' ? p.inclusion.value : 'Unknown applicability'}</p><p>Source: {JSON.stringify(p.source)}</p>
            {p.drivers.policy === 'FIXED_LOW' ? <p>Fixed LOW policy. Uses the configured LOW multiplier.</p> : <div className="driver-grid">{p.drivers.flags.map(f => { const n = f.inputs[0]?.node; const key = n?.kind === 'CONFIGURATION' ? n.key : ''; const value = stored(s, key); return <label key={f.key}>{words(f.key)}{f.derivation ? <p className="muted">Derived: any included HIGH integration/data/AI; unresolved inventory is not false.</p> : <select aria-label={`${u.id} ${f.key}`} disabled={disabled} value={value === null ? 'unknown' : String(value)} onChange={e => void update(key, e.target.value === 'unknown' ? null : e.target.value === 'true', `Reviewer confirmed ${u.id} ${words(f.key)}`)}><option value="unknown">Unknown</option><option value="true">True</option><option value="false">False</option></select>}</label>; })}</div>}
            <p>Score: {p.complexity.score ?? 'N/A'} · Deterministic: {p.complexity.band.state === 'KNOWN' ? p.complexity.band.value : 'Unavailable'} · {p.complexity.rationale}{p.advisoryAIComplexity && ` · AI advisory: ${p.advisoryAIComplexity}`}</p>
            <details><summary>Calculation ledger {u.id}</summary><p>E = quantity × unadjusted baseline × selected multiplier ÷ productivity. Role days = E × share. Money rounds outward per unit and role, then unit contingency is added once.</p>{item ? <><p>Ruleset: {item.ruleSet.version} · Effort {item.confidenceByMetric.effort}, timeline {item.confidenceByMetric.timeline}, ROM {item.confidenceByMetric.commercials}</p><div className="table-wrap"><table><thead><tr><th>Rule step</th><th>Visible inputs</th><th>Result</th></tr></thead><tbody>{item.ledger.map((l, i) => <tr key={i}><td>{l.ruleStep}</td><td>{l.inputValues.map((v, j) => <div key={j}>{String(v.value)}{'unit' in v ? ` ${v.unit}` : ''}</div>)}</td><td>{format(l.result)}</td></tr>)}</tbody></table></div><p>Base {money(item.commercials.base, item.commercials.currency, item.commercials.minorUnitDigits)} · ROM {money(item.commercials.total, item.commercials.currency, item.commercials.minorUnitDigits)}</p><details><summary>Versioned input references</summary><pre>{JSON.stringify(items.find(a => a.payload.unitId === u.id)?.inputs, null, 2)}</pre></details></> : <p>Calculate after reviewing the basis.</p>}</details>
            <details><summary>Trace source and grounding {u.id}</summary>{sourceIds.map(id => { const source = s.artifactSections[id]; return source && source.payload.kind !== 'EstimationUnit' ? <ArtifactReview key={id} section={source} session={s} pending={false} busy={busy} /> : <p key={id}><a href={`#unit-${id}`}>Target canonical unit {id}</a></p>; })}{u.grounding.map(g => { const r = g.source.kind === 'Requirement' ? s.requirements[g.source.id] : s.assumptions[g.source.id]; return <div key={g.source.id}><p>{g.source.kind} {g.source.id}: {g.rationale}</p>{r && <SourceEvidence session={s} anchors={'evidence' in r ? r.evidence : r.sources} />}</div>; })}</details>
          </details>;
        })}</details>;
      })}</section>
      {view && <details className="panel"><summary>Design → work → estimate coverage</summary><p>Assumption-only architecture remains assumption-based and does not add customer requirement coverage. Data domains require a reviewed migration/transformation package decision.</p><div className="table-wrap"><table><thead><tr><th>Accepted design source</th><th>Canonical work / estimate</th><th>Coverage</th></tr></thead><tbody>{view.coverage.map(r => <tr key={r.sourceId}><td>{r.sourceId} · {r.title}<small>{r.grounding.map(g => `${g.source.kind} ${g.source.id}`).join(', ')}</small></td><td>{r.unitIds.join(', ') || 'No package recorded'}<br />{r.estimateIds.join(', ')}</td><td>{r.status}</td></tr>)}</tbody></table></div></details>}
      {summary && <><section className="panel"><h3>Capacity-based timeline ledger</h3><p>Phases are sequential. Role capacity is pooled within each phase; waits add elapsed days, not labor.</p><div className="table-wrap"><table><thead><tr><th>Phase</th><th>Role workloads / limiting roles</th><th>Duration / wait</th><th>Start / finish offsets</th><th>Milestones</th></tr></thead><tbody>{summary.phases.map(p => <tr key={p.key}><td>{p.order} · {p.key}<small>{p.estimateIds.join(', ')}</small></td><td>{p.roleLoads.map(r => <div key={r.roleId}>{r.roleId}: {format(r.effort)}</div>)}Limiting: {p.limitingRoles.join(', ')}</td><td>{format(p.duration)}<br />Wait {format(p.wait)}</td><td>{format(p.startOffset)}<br />{format(p.finishOffset)}<p>Start {p.startDates ? p.startDates.low + "–" + p.startDates.high : "Unavailable"}<br />Finish {p.finishDates ? p.finishDates.low + "–" + p.finishDates.high : "Unavailable"}</p></td><td>{p.milestones.map(m => <div key={m.key}>{m.label}: {format(m.offset)}<br />{m.dates ? m.dates.low + "–" + m.dates.high : "Dates unavailable"}</div>)}</td></tr>)}</tbody></table></div></section><section className="panel" data-testid="estimate-limitations"><h3>Missing inputs and confidence limitations</h3>{summary.missingInputs.map((m, i) => <p key={i}><strong>{'key' in m.node ? m.node.key : 'id' in m.node ? m.node.id : m.field}</strong>: {m.reason}</p>)}{[...new Set(summary.limitations.map(l => l.reason))].map(reason => <p key={reason}>{reason}</p>)}</section></>}
      <details className="panel"><summary>Add a reviewed migration package or environment boundary</summary><p>Data domains and architecture nodes are not automatically priced. Create each explicit package/environment once; separate packages can reference the same domain.</p><label>Boundary type<select value={boundaryType} onChange={e => { setBoundaryType(e.target.value as 'DATA' | 'CLOUD'); setBoundaryRefs([]); }}><option value="DATA">Migration / transformation package</option><option value="CLOUD">Named environment</option></select></label><label>Boundary name<input value={boundaryName} onChange={e => setBoundaryName(e.target.value)} /></label><label>Reviewed boundary<textarea value={boundaryText} onChange={e => setBoundaryText(e.target.value)} /></label><label>Boundary sources<select multiple value={boundaryRefs} onChange={e => setBoundaryRefs(Array.from(e.target.selectedOptions).map(o => o.value))}>{all.filter(a => a.payload.kind === (boundaryType === 'DATA' ? 'DataDomain' : 'ArchitectureComponent')).map(a => <option key={a.id} value={a.id}>{a.id} · {a.title}</option>)}</select></label><button disabled={disabled || !boundaryName || !boundaryText || !boundaryRefs.length} onClick={() => void act('boundaries', { unitType: boundaryType, name: boundaryName, boundary: boundaryText, scopeRefs: boundaryRefs })}>Add boundary for review</button></details>
      <details className="panel"><summary>All versioned configuration and estimation assumptions</summary><p>Each entry has a source/basis, validation and revision. Edit productivity, baseline, multiplier, capacity, calendar, waits, completeness, or other registered assumptions here. JSON <code>null</code> means unknown.</p><label>Configuration entry<select value={configKey} onChange={e => { setConfigKey(e.target.value); setConfigValue(JSON.stringify(stored(s, e.target.value))); }}>{Object.keys(s.configuration.entries).sort().map(key => <option key={key}>{key}</option>)}</select></label><label>Reviewed configuration value (JSON)<textarea value={configValue} onChange={e => setConfigValue(e.target.value)} /></label><label>Configuration basis<input value={basis} onChange={e => setBasis(e.target.value)} /></label><button disabled={disabled || !basis} onClick={() => { try { void update(configKey, JSON.parse(configValue) as unknown); } catch { setError('Configuration value must be valid JSON.'); } }}>Save reviewed configuration</button><div className="table-wrap"><table><thead><tr><th>Key / revision</th><th>Value</th><th>Basis / review</th></tr></thead><tbody>{Object.values(s.configuration.entries).map(e => <tr key={e.key}><td>{e.key} · v{e.revision}</td><td><pre>{JSON.stringify(e.kind === 'VALUE' ? e.value : { owner: e.owner, field: e.field })}</pre></td><td>{e.basis}<br />{e.validation}</td></tr>)}</tbody></table></div></details>
    </>}
  </section>;
}
