import React, { useCallback, useEffect, useState } from 'react';
import type { ScopingSession, NodeRef, QualityGate } from '../../domain/index.js';
import { api, type Mutate, type ScopeStatus } from '../api.js';
import { ArchitectureDiagram } from './ArchitectureDiagram.js';
import { ArtifactReview } from './ArtifactReview.js';

const key = (n: NodeRef) => n.kind === 'CONFIGURATION' ? n.key : n.kind === 'COLLECTION' ? n.name : n.id;
function label(s: ScopingSession, n: NodeRef) { const id = key(n); return n.kind === 'ArtifactSection' ? `${id} · ${s.artifactSections[id]?.title ?? 'Missing section'}` : `${n.kind} ${id}`; }
const value = (v: { value: unknown }) => typeof v.value === 'string' && v.value.length > 240 ? `${v.value.slice(0, 240)}…` : String(v.value);
type Props = { session: ScopingSession; mutate: Mutate; busy: boolean; scope: ScopeStatus | null };
export function ChangeImpact({ session: s, mutate, busy, scope }: Props) {
  const impact = s.lastImpact; const [error, setError] = useState('');
  async function act(path: string) { setError(''); try { await mutate(path); } catch (e) { setError(e instanceof Error ? e.message : 'Update failed.'); } }
  if (!impact) return <section className="panel"><h3>Change impact</h3><p>Edit a reviewed requirement, assumption or configuration to inspect affected and preserved areas.</p></section>;
  const current = impact.evaluatedRevision === s.revision;
  const affected = [...impact.direct, ...impact.transitive].filter(n => n.kind === 'ArtifactSection');
  const generated = new Set(impact.regenerationTargets.map(key)), numerical = new Set(impact.recalculationTargets.map(key));
  return <section className="panel" data-testid="change-impact"><div className="row"><h3>Change impact</h3><span className={`chip ${current ? 'reviewed' : 'draft'}`}>{current ? 'CURRENT' : 'OBSOLETE'} · revision {impact.evaluatedRevision}</span></div>
    <p>Changes affect declared consumers. Reviewed content outside these dependencies is preserved. Potential impacts wait for accepted upstream values.</p>
    <div className="change-values">{impact.change?.changes.filter(c => ['Requirement', 'Assumption', 'CONFIGURATION'].includes(c.node.kind)).map(c => <div key={key(c.node)}><strong>{label(s, c.node)}</strong>{c.fieldChanges?.map(f => <p key={f.field}><code>{f.field}</code>: <span>{value(f.before)}</span> → <strong>{value(f.after)}</strong></p>)}</div>)}</div>
    {error && <p role="alert" className="error">{error}</p>}
    <div className="actions"><button className="primary" disabled={busy || !current || !scope?.eligibility.eligible || !generated.size} onClick={() => void act('impact/regenerate')}>Regenerate affected content</button><button disabled={busy || !current || !scope?.eligibility.eligible || !numerical.size || generated.size > 0} onClick={() => void act('impact/recalculate')}>Recalculate affected estimate</button><a href="#selective-proposals">Review proposals</a></div>
    {!scope?.eligibility.eligible && <p className="muted">Review and approve the changed scope before new generation or calculation. Historical review and content freshness remain separate.</p>}
    <div className="impact-columns"><section data-testid="impact-affected"><h4>Affected ({affected.length})</h4>{!affected.length && <p>No currently declared section consumes this edit.</p>}{affected.map(n => {
      const reason = impact.reasons.find(r => key(r.node) === key(n) && r.node.kind === n.kind); const a = n.kind === 'ArtifactSection' ? s.artifactSections[n.id] : undefined; const slice = impact.affectedSlices.find(r => r.id === key(n));
      return <article className="impact-item" key={key(n)}><strong>{label(s, n)}</strong><p><span className="chip">{reason?.direct ? 'DIRECT' : 'TRANSITIVE'}</span> <span className="chip">{a?.freshness}</span> {generated.has(key(n)) ? 'REGENERATE' : numerical.has(key(n)) ? 'RECALCULATE' : 'COMPARE AFTER ACCEPTANCE'}</p>{slice && <p>Refresh: {slice.affected.join(', ')}<br /><span className="muted">Preserve: {slice.unaffected.join(', ') || 'No independent metric slice'}</span></p>}<details><summary>Why is this affected?</summary><p>{reason?.reason}</p><ol className="impact-path">{reason?.path.map((node, i) => <li key={i}>{label(s, node)}</li>)}</ol></details></article>;
    })}</section><section data-testid="impact-unaffected"><h4>Unaffected reviewed content ({impact.unaffectedReviewed.length})</h4><p className="muted">Explicitly checked against declared dependencies; retained payload and review.</p>{impact.unaffectedReviewed.map(n => <p key={n.id}>{label(s, { kind: 'ArtifactSection', id: n.id })} <span className="chip reviewed">REVIEWED · CURRENT</span></p>)}</section></div>
    {!!impact.unknown.length && <details><summary>UNKNOWN IMPACT ({impact.unknown.length})</summary><p>Consumption declarations or references are incomplete. These areas are not certified unaffected.</p>{impact.unknown.map(n => <p key={`${n.kind}-${key(n)}`}>{label(s, n)}</p>)}</details>}
    {!!impact.diagnostics.length && <details><summary>Dependency integrity findings</summary>{impact.diagnostics.map((d, i) => <p key={i}>{label(s, d.node)}: {d.reason}</p>)}</details>}
    <p className="muted">Coverage and quality are reevaluated for the current revision. Diagrams rerender from accepted component changes.</p>
  </section>;
}
export function Quality(props: Props) {
  const { session: s, mutate, busy } = props; const [error, setError] = useState(''); const [view, setView] = useState<{ gate: QualityGate | null; current: boolean } | null>(null); const [selected, setSelected] = useState<NodeRef | null>(null);
  useEffect(() => { let active = true; void api(`/api/sessions/${s.id}/quality`).then(v => { if (active) setView(v as NonNullable<typeof view>); }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Quality status unavailable.'); }); return () => { active = false; }; }, [s.id, s.revision, s.operationalRevision]);
  const [diagram, setDiagram] = useState<{ revision: number; success: boolean | null } | null>(null);
  const onRender = useCallback((success: boolean | null) => setDiagram({ revision: s.revision, success }), [s.revision]);
  async function act(path: string, body?: object) { setError(''); try { await mutate(path, body); } catch (e) { setError(e instanceof Error ? e.message : 'Review failed.'); } }
  const gate = view?.gate; const pending = Object.values(s.generationRuns).filter(r => r.acceptance === 'PENDING' && r.fixtureVariant?.startsWith('phase4')).flatMap(r => r.proposals.flatMap(p => p.action !== 'RETIRE' && p.candidate.kind === 'ArtifactSection' && !r.decisions?.[p.candidate.record.id] ? [{ run: r, section: p.candidate.record }] : []));
  return <>
    <section className="panel" data-testid="quality-gate"><div className="row"><h3>Quality gate</h3><span className={`chip ${gate?.status === 'PASS' && view?.current ? 'reviewed' : 'draft'}`}>{view?.current ? gate?.status : 'NOT EVALUATED · current revision'}</span></div><p>Deterministic coverage, grounding, delivery, AI safeguards, technology and estimate checks. Warnings require review; integrity errors block the gate.</p><button className="primary" disabled={busy || diagram?.revision !== s.revision || diagram.success === null} onClick={() => void act('quality/evaluate', { diagramRendered: diagram?.success })}>Run quality gate</button>{error && <p role="alert" className="error">{error}</p>}
      {gate && view?.current && <><p className="muted">Revision {gate.evaluatedRevision} · rules {gate.ruleVersion}</p><div className="field-grid">{(['scope', 'design', 'delivery'] as const).map(stage => <div key={stage}><h4>{stage} coverage</h4><strong>{gate.coverage.eligibleRequirementIds.length ? `${gate.coverage[stage].coveredIds.length}/${gate.coverage.eligibleRequirementIds.length}` : 'N/A'}</strong><p>Uncovered: {gate.coverage[stage].uncoveredIds.join(', ') || 'None'}</p></div>)}</div><p>High-priority scope coverage: {gate.coverage.highPriority.eligible ? `${gate.coverage.highPriority.covered}/${gate.coverage.highPriority.eligible}` : 'N/A'}</p><details><summary>Excluded requirements ({gate.coverage.excluded.length})</summary>{gate.coverage.excluded.map(r => <p key={r.id}>{r.id}: {r.reason}</p>)}</details>
      <h4>Findings ({gate.issues.length})</h4>{!gate.issues.length && <p>No current findings.</p>}{gate.issues.map(issue => <article className="quality-finding" key={issue.key}><div className="row"><strong>{issue.type.replaceAll('_', ' ')}</strong><span className={`chip ${issue.blocking ? 'draft' : ''}`}>{issue.severity} · {issue.status}</span></div><p>{issue.message}</p><div className="actions">{issue.related.map((n, i) => <button key={i} onClick={() => setSelected(n)}>{label(s, n)}</button>)}</div><small>{issue.ruleId} · revision {issue.evaluatedRevision}</small></article>)}</>}
    </section>
    <details className="panel"><summary>Architecture rendering check</summary><ArchitectureDiagram sections={Object.values(s.artifactSections).filter(a => a.lifecycle === 'ACTIVE' && a.review === 'REVIEWED' && a.freshness === 'CURRENT')} onRender={onRender} /></details>
    {selected && <section className="panel"><div className="row"><h3>Related content: {label(s, selected)}</h3><button onClick={() => setSelected(null)}>Close related content</button></div>{selected.kind === 'ArtifactSection' && s.artifactSections[selected.id] ? <ArtifactReview section={s.artifactSections[selected.id]!} session={s} pending={false} busy={busy} /> : <pre>{JSON.stringify(selected.kind === 'Requirement' ? s.requirements[selected.id] : selected.kind === 'Assumption' ? s.assumptions[selected.id] : selected.kind === 'Question' ? s.questions[selected.id] : selected.kind === 'CONFIGURATION' ? s.configuration.entries[selected.key] : selected, null, 2)}</pre>}</section>}
    <ChangeImpact {...props} />
    <section className="panel" id="selective-proposals" data-testid="selective-proposals"><h3>Before / after review</h3><p>Only acceptance replaces the selected section. Rejection retains the previous accepted stale content.</p>{!pending.length && <p>No pending selective proposals.</p>}{pending.map(({ run, section }) => <div className="replacement-review" key={`${run.id}-${section.id}`}><h4>{section.title} · {section.id}</h4><details><summary>Previous accepted content</summary>{s.artifactSections[section.id] && <ArtifactReview section={s.artifactSections[section.id]!} session={s} pending={false} busy={busy} />}</details><h5>Proposed replacement</h5><ArtifactReview section={section} session={s} pending busy={busy} accept={() => void act(`runs/${run.id}/sections/${section.id}/review`, { decision: 'ACCEPTED' })} reject={() => void act(`runs/${run.id}/sections/${section.id}/review`, { decision: 'REJECTED' })} /><details><summary>Change cause and affected path</summary>{s.lastImpact?.reasons.filter(r => r.node.kind === 'ArtifactSection' && r.node.id === section.id).map((r, i) => <p key={i}>{r.reason}<br />{r.path.map(n => label(s, n)).join(' → ')}</p>)}</details></div>)}</section>
    <section className="panel"><h3>Final package / export: Phase 5</h3><p>Integrated package assembly and download are not available in Phase 4.</p></section>
  </>;
}
